# Generated by Django 5.2.4 on 2025-09-17 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_expenseassignment_split_bill_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyGiven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "given_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_given_out",
                        to="api.splitbillmember",
                    ),
                ),
                (
                    "given_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_received",
                        to="api.splitbillmember",
                    ),
                ),
                (
                    "split_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_given",
                        to="api.splitbill",
                    ),
                ),
            ],
        ),
    ]
