# Generated by Django 5.2.4 on 2025-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="splitbill",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
