# Generated by Django 5.2.4 on 2025-08-20 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_expense_assigned_to_expenseassignment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenseassignment",
            old_name="amount",
            new_name="share_amount",
        ),
    ]
