# Generated by Django 5.2.4 on 2025-08-20 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_amount_expenseassignment_share_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenseassignment",
            old_name="username",
            new_name="user",
        ),
    ]
