# Generated by Django 5.2.4 on 2025-08-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_username_expenseassignment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="split_type",
            field=models.CharField(
                choices=[
                    ("equal", "Equal"),
                    ("percentage", "Percentage"),
                    ("custom", "Custom"),
                ],
                default="equal",
                max_length=20,
            ),
        ),
    ]
