# Generated by Django 5.2.4 on 2025-08-25 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_expense_split_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="date_created",
        ),
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
